name: hook_atos
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+2

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  path_provider: ^2.0.11
  location_permissions: any
  flutter_svg: ^1.1.4
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  url_launcher: ^6.1.5
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  tbib_toast: ^0.0.2
  internet_connection_checker: ^0.0.1+4
  dio: ^4.0.6
  awesome_dialog: ^2.2.1
  image_picker: ^0.8.5+3
  connectivity_plus: ^2.3.6+1
  permission_handler:
  background_locator_2: ^2.0.6
  expansion_card: ^0.1.0
  background_location:

    git:
      url: https://github.com/hilalbaig/background_location.git
      ref: master


  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  firebase_storage: ^11.1.0
  cloud_firestore: ^4.5.0
  firebase_messaging: ^14.4.0
  device_info_plus: ^4.1.2
  image_cropper: ^3.0.0
  http: ^0.13.5
  flutter_local_notifications: ^13.0.0
  tap_to_expand: ^0.6.1

  location: ^4.4.0
  geolocator: ^9.0.1
  google_maps_flutter: ^2.1.12
  geocoding: ^2.0.5

  flutter_spinkit: ^5.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf
    - family: Wahran
      fonts:
        - asset: assets/fonts/Wahran-Regular.otf
          style: italic
          weight: 700


